### ISSUE TITLE
Support "file" as source for callbacks' request body

### ISSUE THREAD

**Issue by x80486** [apimastery/APISimulator#12]
According to the documentation, this is *still* not supported, but I think it would be great to have this...so just filing an issue here to track this, whenever it gets implemented 😉

**Comment by apisim** [comment]
Gotcha.

It is a bit inconsistent with the support of `file` elsewhere, agreed. I frankly don't remember why it wasn't implemented "day one"...but it shouldn't be complicated to implement.

**Comment by apisim** [comment]
This enhancement was included in the just released v1.10. 

Give it a try when you get a chance, @x80486 
Thanks!

**Comment by x80486** [comment]
And this one is also working like a charm :tropical_drink:

```yaml
response:
  callback: # https://apisimulator.io/docs/latest/standalone-api-simulator/callback.html
    http1:
      body:
        file: ${simlet.path}/character-subscription.request.json
      from: template
    ...
```

```json
{
  "first_name": "${_json.evalJsonPath(_request.bodyText, '.first_name')}",
  "last_name": "${_json.evalJsonPath(_request.bodyText, '.last_name')}",
  "age": ${_json.evalJsonPath(_request.bodyText, '.age')},
  "subscriber_id": "${character_id}"
}
```

![image](https://user-images.githubusercontent.com/34633617/159197210-9c610946-bf07-4862-87bd-805a5a506873.png)
