### ISSUE TITLE
Allow to read request body on the fly

### ISSUE THREAD

**Issue by x80486** [apimastery/APISimulator#14]
API Simulator has a way to acquire the value from the request body by using "parameters", for instance:

```yaml
ProductID:
  element: ".product.id"
  from: body
  is: parameter
```

Is it possible to support this "on the fly"? For instance, we can do `${_request.body.product.id}` directly, because we are only interested on this value to put it in a template, but not to use it on a _matcher_.
