### ISSUE TITLE
Config file for environment-specific settings

### ISSUE THREAD

**Issue by x80486** [apimastery/APISimulator#15]
As of version `1.9`, it's not possible to provide an external config file, or just augment the default one with a (preferable predefined) key in order to read environment-specific settings.

For instance, when doing `callback`s, the hostname will usually change between different environments: `test`, `qa`, etc.

If the default config file defines a predefined key (e.g.: `application`) that we can use for such things, then it would be possible to place any values that we need, maintaining the same (YAML-like structure). Eventually, there has to be a way to read these within the simulations...so that's needed as well 🤣

Something like this:

```yaml
application: # this is for us, the users ;)
  callbacks:
    - service: foo
      hostname: env.foo.tld
admin: https
host: 1.2.3.4
```

Actually, that's quite complicated, because the structure for the configuration is not known beforehand, so I'm not sure how to approach this one right away 🤔
