### ISSUE TITLE
Enhance DSL to loop from data sources

### ISSUE THREAD

**Issue by x80486** [apimastery/APISimulator#17]
Say for instance I have a CSV file with data used throughout a set of resources. Currently, I can't find a way to build JSON responses based on (the entire or a subset of) the data. I think probably using the `Simula Template Scriptlets`.

Would it be possible to enhance the DSL to accomplish such tasks with lists/iterators?

An example might make things more clear:

```yaml
simlet: retrieve-people

# ...parameters
character:
  file: ${simlets.path}/people.csv
  from: csv
  is: parameter
  keys:
    - person_id

request:
  - header: accept
    equals: application/json
  - method: GET
  - uriPathPattern: /api/people

response:
  body:
    file: ${simlet.path}/people.response.json
  from: template
  headers:
    - name: content-type
      value: application/json
  status: 200
  template: Simula
```

```csv
person_id,first_name,last_name
19b766af-43e5-4695-8593-452b62fdf361,Smith,Johnson
3bd23f11-e668-4c3f-ba74-3d45e6033c46,Arabella,Foster
baf5dade-eabd-4d54-98f7-e90f6953108f,Quentin,Kelley
```

```json
[
  {
    "first_name": "${person['first_name']}",
    "last_name": "${person['last_name']}",
    "_id": "${person_id}"
  },
]
```
