### ISSUE TITLE
Provide a way to match request body against JSON schema

### ISSUE THREAD

**Issue by x80486** [apimastery/APISimulator#2]
I've read the [Body Matching](https://apisimulator.io/docs/1.7/standalone-api-simulator/request-matching.html#body-matching) section. I'm aware **something similar** can be achieved by using JSONPath, but the outcome won't be the same. Moreover, teams already employ JSON schemas or Open API definitions to check end-point contracts — so that's a time saver.

I think it would be great is API Simulator could validate a given request body against a corresponding [JSON schema](https://json-schema.org/). For instance, [MockServer](https://www.mock-server.com/mock_server/creating_expectations.html#button_match_request_by_body_with_json_schema) does something similar:

```json
...
  "body": {
    "type": "JSON_SCHEMA",
    "jsonSchema": "schemas/create-entity.schema.json"
  },
...
```

**Comment by apisim** [comment]
Hi @x80486 

This isn't currently supported. Labeled it as an "enhacement".
Thanks!

**Comment by apisim** [comment]
Just to make sure I understand

> validate a given request body against a corresponding JSON schema

in the context of simulating an API with API Simulator:
_API Simulator validating the body of an HTTP request against a given JSON Schema is as part of matching incoming requests to determine which response to return._

Is this what the feature is about?

**Comment by x80486** [comment]
Yes, basically, when we model a `POST` operation, we usually want to make sure certain fields are there, if not, we respond accordingly. A JSON schema validates that be body sent is valid according to the schema applied to the simulation.

If you take a look at what MockServer does I think it would be easier — but it's more to _match_ than actually validate.

**Comment by apisim** [comment]
Got it, thanks.

In the meantime, if you haven't already, you can check out the support for [Multiple Responses](https://apisimulator.io/docs/1.7/standalone-api-simulator/response-configuration.html#multiple-responses) in API Simulator and especially the example that demonstrates an approach to returning different responses based on the validity of input elements.

**Comment by x80486** [comment]
By the way, after thinking about this one for a while, it sort of makes and at the same time makes no sense to have it implemented. I guess it would be a nice-to-have for some "rare" use cases, but I think it doesn't really fit on this kind of software.

If you would like to implement it, leave it opened...otherwise, feel free to close it 😁

**Comment by x80486** [comment]
Another approach on solving this problem could be by supporting [RAML data type definitions](https://raml.org). It makes it interesting because one can make sure the input data is actually structured in the expected form.

Something like this:

```yaml
#%RAML 1.0 DataType

type: object
properties:
  employee_id: 
    type: integer
    required: true
    minimum: 8
  first_name: 
    type: string
    required: true
    minLength: 1
    maxLength: 10
    pattern: ^[A-Za-z]*
  last_name: 
    type: string
    required: true
    minLength: 1
    maxLength: 10
    pattern: ^[A-Za-z]*
  email:
    pattern: ^.+@.+\..+$
  ...
```

Perhaps a new DSL key to allow a reference to a file with the RAML data type definitions for a given operation. Maybe the DSL is only available for those HTTP operations that can send payloads: `POST`, `PUT`, etc.
