### ISSUE TITLE
Does the SQL Data Store feature support other databases than H2?

### ISSUE THREAD

**Issue by felipetofoli** [apimastery/APISimulator#22]
Hi!

I've been trying the feature documented here [SQL Data Store](https://apisimulator.io/docs/1.11/standalone-api-simulator/simlet-parameters.html#sql-data-store).

When I tested with the H2 database, the feature worked as expected.

But, when I tried other driver classes, I got errors:

When trying to connect to MS SQL Server
> java.lang.IllegalStateException: Failed to load JDBC driver class 'com.microsoft.sqlserver.jdbc.SQLServerDriver']

A failure also happened when trying to use `org.postgresql.Driver` driver class.

The configuration used:

```yaml
ProductData:
  is: parameter
  from: sql

  connection:
    # Currently, pooled connections are not supported
    uses: driver # pool
    
    # Driver's fully-qualified class name
    driver: "com.microsoft.sqlserver.jdbc.SQLServerDriver"

    ...

```

So, my question is: Does the SQL Data Store feature support other databases than H2?

Thanks!
