### ISSUE TITLE
force refresh calculated parameters

### ISSUE THREAD

**Issue by enigmatiqk** [apimastery/APISimulator#26]
Hi,

about calculated parameter (uid, random xxx, request counter, ....)

i would like force refresh for the same request.
why ? when the request return multi data blocs, the parameters has always same value

in this exemple, all peoples will have the same uuid: 

```
peopleID:
  is: parameter
  from: uuid

[...]

response:
  from: template
  status: 200
  headers:
    - name: content-type
      value: application/json
  body: `
[
<%
for (person in people) {
  write '  {\n'
  write '    "first_name": "' + person['first_name'] + '",\n'
  write '    "last_name": "' + person['last_name'] + '",\n'
  write '    "_id": "' + peopleID + '",\n'
  write '  },\n'
}%>]
`
```

i would like this functionnality : 

```
response:
  from: template
  status: 200
  headers:
    - name: content-type
      value: application/json
  body: `
[
<%
for (person in people) {
  write '  {\n'
  write '    "first_name": "' + person['first_name'] + '",\n'
  write '    "last_name": "' + person['last_name'] + '",\n'
  write '    "_id": "' + peopleID + '",\n'
  write '  },\n'
  refresh(peopleID)
}%>]
`
```

or another technical solution (like scope by loop)

no scope by "use", this case is not compatible with this exemple : 

```
response:
  from: template
  status: 200
  headers:
    - name: content-type
      value: application/json
  body: `
[
<%
for (person in people) {
  write '  {\n'
  write '    "first_name": "' + person['first_name'] + '",\n'
  write '    "last_name": "' + person['last_name'] + '",\n'
  write '    "_id": "' + peopleID + '",\n'
  write '    "link": "http://myurl/people/' + peopleID + '",\n'
  write '  },\n'
  refresh(peopleID)
}%>]
`
```

thanks

**Comment by apisim** [comment]
HI @enigmatiqk,

It makes sense what you are asking.
Please take a look at `isSnapshot: false` as described [here](https://apisimulator.io/docs/1.11/standalone-api-simulator/simlet-parameters.html#configuring-parameters).

A full example:
```yaml
simlet: parameter-snapshot-false

request:
  - method: GET
  - uriPath: /tests/parameter-snapshot-false


uuidParm:
  is: parameter
  from: uuid
  isSnapshot: false


response:
  from: template
  headers:
   - "content-type: application/json"
  body: `
{
  "uuid-1": "${ uuidParm }",
  "uuid-2": "${ uuidParm }"
}
`
```

`uuid-1` and `uuid-2` will have different values when the parameter is defined with `isSnapshot: false`. They will be the same when `isSnapshot: true`, which is also the default.
