### ISSUE TITLE
Cors are not handled automatically ...

### ISSUE THREAD

**Issue by enigmatiqk** [apimastery/APISimulator#28]
hello !

I have a problem with CORS, the documentation say it's handled automatically but not with me :( 
https://apisimulator.io/docs/latest/standalone-api-simulator/admin-apis.html#cors

version 1.12
simple api , 1 simplet simlet from example : 

```
matchers:
- method: GET

- where: uriPathPattern
  matches: /greetings/{name}


NameParm:
  is: parameter
  from: uriPathPattern
  pattern: /greetings/{name}


response:
  from: template
  template: Simula
  body: "Greetings, ${NameParm}!"
```

call with "OPTIONS" method does not works
call with "Origin" header does not add "Access-Control-Allow-Origin" header

i not see any info about "Access-Control-Allow-Methods" and "Access-Control-Allow-Headers" headers for cors ?

i have search to add default headers ... without result ...

please help me ...

**Comment by enigmatiqk** [comment]
I've just seen that the corns manager is in the administration area.  

Please tell me that the cors handler is also in the simulation area ...

**Comment by apisim** [comment]
Yes, @enigmatiqk - CORS is handled automatically for the Admin APIs. For Custom APIs, CORS handling can be simulated on as needed basis.

**Comment by apisim** [comment]
Below is an example of how to simulate handling CORS. Place these simlets in a simulation's `apisim.yaml` file. Of course - it is also possible to place them in separate directories as explained in [Directory per Simlet](https://apisimulator.io/docs/latest/standalone-api-simulator/api-simulation-configuration.html#directory-per-simlet).

```yaml
# This simlet handles preflight OPTIONS requests in a generic way
simlet: cors-options

request:
  - method: OPTIONS
  - where: uriPath
    isLike: "/.*"

response:
  from: stub
  status: 204
  headers:
   - "Access-Control-Allow-Origin: *"
   - "Access-Control-Allow-Methods: *"
   - "Access-Control-Allow-Headers: *"
   - "Access-Control-Max-Age: 86400"
   - "Vary: Accept-Encoding, Origin"
---
# The greetings example for CORS requests. 
# In essence, it optionally returns Access-Control-Allow-Origin header in the
# response that echoes the value of the Origin header from the request, if present
simlet: cors-greetings

request:
- method: GET
- uriPathPattern: /greetings/{name}

OriginHeaderParm:
  is: parameter
  from: header
  named: "Origin"

Name:
  is: parameter
  from: uriPathPattern
  pattern: /greetings/{name}

response:
  from: template
  headers:
    - header: "<% if (OriginHeaderParm != null && OriginHeaderParm.trim().length() > 0)
                { %>Access-Control-Allow-Origin: ${OriginHeaderParm}\r\n<% } %>"
      optional: true
  body: "Greetings, ${Name}!"
```

The approach of returning optional header is described in [Scriptlets in Header Fields](https://apisimulator.io/docs/latest/standalone-api-simulator/simula-template-scriptlets.html#scriptlets-in-header-fields).

Would this work for you, @enigmatiqk?
