### ISSUE TITLE
disallow additionalQueryParameters in uri

### ISSUE THREAD

**Issue by justinezahiri** [apimastery/APISimulator#29]
It would be great if you could add a `additionalQueryParameters` to allow or disallow parameters for a given `uriPath`

```
//simlet.yaml

request:
  - method: GET
  - uriPath: '/some-api'
  - additionalQueryParameters: false
  ```
  
 Thanks !

**Comment by apisim** [comment]
Hi @justinezahiri,

Would something like this work?
```yaml
simlet: match-req-without-queryParms

request:
  - method: GET
  - uriPath: /examples/match-req-without-queryParms
  - where: parameter
    named: QueryParmsCount
    equals: 0

QueryParmsCount:
  is: parameter
  from: uriQueryParameters
  eval: return _.count()

response:
  from: stub
  headers:
    - "content-type: application/text"
  body: "The request had no query string parameters."
```

We could also use [Request Object](https://apisimulator.io/docs/latest/standalone-api-simulator/request-object.html) with some scripting as well.


Happy API Simulating!

**Comment by justinezahiri** [comment]
Thank you for you response. It could work but in my case what I wanted to do is to allow one or more parameters from a strict list of parameters and disallow any other parameter. 

something like : 

```
//simlet.yaml

request:
  - method: GET
  - uriPath: '/some-api'
  - where: parameter
  - named: someParameter  // (can be a list)
  - additionalQueryParameters: false
  ```

**Comment by apisim** [comment]
OK. If it is (quote) "a strict list of [query] parameters", we could make sure the number of query parameters is exactly as expected and no more, along with matching the values of the expected query parameters.

Something like:
```yaml
//simlet.yaml

request:
  - method: GET
  - uriPath: '/some-api'
  - where: parameter
  - named: someQueryParameter1
    // matching condition...
  - ...
  - where: parameter
  - named: someQueryParameterN
    // matching condition...
  - where: parameter
    named: QueryParmsCount
    equals: <number-of-expected-query-parameters>

QueryParmsCount:
  is: parameter
  from: uriQueryParameters
  eval: return _.count()
```

Thoughts?

**Comment by justinezahiri** [comment]
Thank you again for your response, it's quite good also. But my API can have one or more parameters, it's not always the same number. The important thing i want to test here is their names, and to allow only a certain list of parameters names.

**Comment by apisim** [comment]
We can test if a query parameter with certain name is in the URI using [uriQueryParameter](https://apisimulator.io/docs/latest/standalone-api-simulator/simlet-parameters.html#uri). Like in:

```yaml
request:
  - method: GET
  - uriPath: '/some-api'
  - where: parameter
  - named: SomeQueryParameter1
    exists: true
  - where: parameter
    named: QueryParmsCount
    equals: 1

SomeQueryParameter1:
  is: parameter
  from: uriQueryParameter
  named: "query-string-parameter-name"

QueryParmsCount:
  is: parameter
  from: uriQueryParameters
  eval: return _.count()
```
