### ISSUE TITLE
Augment Template Functions

### ISSUE THREAD

**Issue by x80486** [apimastery/APISimulator#4]
Template Functions are great. The library reference for `random` offers several functions, but I think a good addition to it could be something like `com.github.javafaker:javafaker` in order to get meaningful values for common return types, like: addresses, states, first names, last names, credit card numbers, etc.

> I'm aware something similar can be achieved by using a random token, but it's not quite the same. This would be similar to what Postman already have implemented: https://learning.postman.com/docs/writing-scripts/script-references/variables-list/

**Comment by apisim** [comment]
Hi @x80486 

Have you come across [Random Elements from List](https://apisimulator.io/docs/latest/standalone-api-simulator/simlet-parameters.html#random-elements-from-list)? Something like:

```
...
RandomFirstName:
  is: parameter
  from: list
  list: [ "Anna", "Bill", "Mark", "Sofia" ]
  pick: 1
...
response:
  from: template
  body: Hello, ${RandomFirstName}!
```

Noticed that the source list can also come from an external file.
