### ISSUE TITLE
Tricky Type Inference With External JSON Files

### ISSUE THREAD

**Issue by x80486** [apimastery/APISimulator#6]
Imagine there is a simulation like this one (excerpt):

```yaml
---
simlet: Identifier

parameters: # <- why is this going away if it's super-useful to organize all parameters under one key!
  - age:
      from: number
      range:
        min: 20
        max: 40

request:
  ...

response:
  from: template
  template: Simula
  headers:
    - name: content-type
      value: "application/json"
  status: 200
  body:
    file: "${sim.path}/umbrella-api/operation-one/files/response/model-identifier/get-response.json"
```

...and `get-response.json` could be something like:

```json
{
  "first_name": "Rahy",
  "last_name": "Hellbleeder",
  "age": "${age}", !!!
  "_id": "${_random.uuid()}"
}
```

As you can notice by the `!!!`, `age` is being sent as a `string`, instead of a `number`. The reason it needs to be wrapped into double quotes is to make `get-response.json` a valid JSON.

> It works fine if the double quotes are removed, but then auto-formatting and some checks placed on the project's pipeline for JSON/YAML files will fail.

Is there a work-around for this?

**Comment by x80486** [comment]
I think a safe bet would be to use the `Formatter` class (or something along those lines) and enforce the type based on the dynamic value(s), regardless of the JSON representation — in this case, the double-quotes wrapped thing.

**Comment by apisim** [comment]
Hi @x80486 

I'm not sure understand. This is a valid JSON:

```
{
  "first_name": "Rahy",
  "last_name": "Hellbleeder",
  "age": 23,
  "_id": "040595e1-ddc9-4699-ba75-82c8d5a04c6e"
}
````
That is - the age value as a number, not a (double-quoted) string. Just run it through any online JSON validator/linter.

Below is a complete, working simlet:

```
---
simlet: Identifier

import:
  random: _random

parameters:
  - age:
      from: number
      range:
        min: 20
        max: 40

request:
  - method: GET
  - uriPath: /number-in-json

response:
  from: template
  template: Simula
  headers:
    - name: content-type
      value: "application/json"
  status: 200
  body:
    file: "${sim.path}/umbrella-api/model-identifier/get-response.json"
````
...and this is the content of the `${sim.path}/umbrella-api/model-identifier/get-response.json` file (with `${sim.path}` substituted for the simulation's directory):

```
{
  "first_name": "Rahy",
  "last_name": "Hellbleeder",
  "age": ${age},
  "_id": "${_random.uuid()}"
}
```

When running locally, this is a way to call it using `curl` (`-v` is for verbose output):
```
curl -v http://localhost:6090/number-in-json
```

Is the ask to have API Simulator automatically surround with double quotes the values `${}` placeholders resolve to if those values are strings?
